/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guimenuk;

import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author KisváradiMárton(Szf_
 */
public class menukGUI extends javax.swing.JFrame {

    /**
     * Creates new form menukGUI
     */
    public menukGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nevTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        szakValasztoComboBox = new javax.swing.JComboBox<>();
        hirlevelChckBox = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSave = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuQuit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Név:");

        jLabel2.setText("Szak:");

        szakValasztoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Szak választása", "Szoftverfejlesztő- és tesztelő", "Rendszergazda", "Utca Seprő" }));

        hirlevelChckBox.setText("Hírlevél");

        jMenu1.setText("Program");

        jMenuItem1.setText("Betöltés");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        mnuSave.setText("Mentés...");
        mnuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSave);
        jMenu1.add(jSeparator2);

        mnuQuit.setText("Kilépés");
        mnuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuQuit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(nevTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(szakValasztoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hirlevelChckBox)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nevTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(szakValasztoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hirlevelChckBox))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuitActionPerformed
        quit(); 
        
    }//GEN-LAST:event_mnuQuitActionPerformed


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        quit();
//        JOptionPane.showMessageDialog(rootPane, msg, title, msgType);
    }//GEN-LAST:event_formWindowClosing

    private void mnuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaveActionPerformed
          Object[] options = {szakValasztoComboBox.getItemAt(1), szakValasztoComboBox.getItemAt(2), szakValasztoComboBox.getItemAt(3)};
          if(szakValasztoComboBox.getSelectedItem() == "Szak választása") {
              int option = JOptionPane.showOptionDialog(null, "Válassz egy szakot:", "Hiba!", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,options[0]);
              //System.out.println(option);
              szakValasztoComboBox.setSelectedIndex(option+1);
          }
          
          JFileChooser jfc = new JFileChooser(System.getProperty("user.dir")); //Aktualis projekt
          int answear = jfc.showSaveDialog(this);
          System.out.println(answear);
   
          
          if(answear == JFileChooser.APPROVE_OPTION) {
//              System.out.println(jfc.getSelectedFile());
              File kivalasztottFajl = jfc.getSelectedFile();
              Path path = Path.of(kivalasztottFajl.getAbsolutePath());
              try {
                  Files.writeString(path, tartalom());
              } catch (IOException ex) {
                  JOptionPane.showMessageDialog(rootPane, "JO hiba!\n" + ex.getMessage());
                  Logger.getLogger(menukGUI.class.getName()).log(Level.SEVERE, null, ex);
              }
          };
    }//GEN-LAST:event_mnuSaveActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser jfc = new JFileChooser(System.getProperty("user.dir"));
        int answear = jfc.showSaveDialog(this);
        System.out.println(answear);
        
        if(answear == JFileChooser.APPROVE_OPTION) {
            File kivalasztottFile = jfc.getSelectedFile();
            Path path = Path.of(kivalasztottFile.getAbsolutePath());
            try {
                String szoveg = Files.readString(path);
                String[] sorok = szoveg.split("\n");
                String nev = sorok[0].split(" ")[1];
                String szak = sorok[1].split(":")[1].trim();
                
                
                System.out.println(nev);
                nevTxtField.setText(nev);
                
                System.out.println(szak);
                szakValasztoComboBox.setSelectedItem(szak);
                
                //hirlevelChckBox.setSelected();
            } catch (IOException ex) {
                Logger.getLogger(menukGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private String tartalom() {
        return "Név: " + nevTxtField.getText() + "\nSzak: " + szakValasztoComboBox.getSelectedItem() + "\nHírlevél feliratkozás: " + hirlevelChckBox.isSelected();
    }

    private void quit() throws HeadlessException {
        String msg = "Biztosan kilép?";
        String title = "Kilépés";
        int msgType = JOptionPane.QUESTION_MESSAGE;
        int optType = JOptionPane.YES_NO_OPTION;
//        JOptionPane.showMessageDialog(rootPane, msg, title, msgType);
        int answear = JOptionPane.showConfirmDialog(this, msg, title, optType);

        if(answear == JOptionPane.YES_OPTION) {
            int hibaKod = 0;
            System.exit(hibaKod);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menukGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menukGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menukGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menukGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menukGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox hirlevelChckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuQuit;
    private javax.swing.JMenuItem mnuSave;
    private javax.swing.JTextField nevTxtField;
    private javax.swing.JComboBox<String> szakValasztoComboBox;
    // End of variables declaration//GEN-END:variables
}
